### PR TITLE
Attempt to solve race condition affecting ignoreCbus #10

### PR DESCRIPTION
**Pull request by autoSteve**
@geoffwatts, give the code in this draft pull a try in a test resident to see if it avoids race.

The first thing I've added is a timeout for ignoreCbus flags. If your suspected race condition is really setting ignoreCbus and then it never gets cleared, then this draft will kill the ignore flag after 0.5 seconds and log the event.

There is a potential for race condition, though. The main loop does eventbus step() then MQTT loop(), then it processes queued C-Bus messages first, and then immediately after it processes the MQTT messages. A MQTT change that affected the same GA could mess things up.

So the second thing I have changed is this sequence to step(), process C-Bus, loop(), process MQTT.

### CODE REVIEW

**Comment by autoSteve** [comment]
This all still has issues. Working on it.

**Comment by geoffwatts** [comment]
Just got home and took this out for a spin, Steve, and having some slight carnage:

Can't seem to set groups to off now from the cbus UI.

* string: Error processing outstanding CBus messages: [string "Resident"]:408: attempt to compare number with nil
* string: Warning: Removed orphaned C-Bus ignore flag for 0/56/213, the expected level 571 was never received - value when set was 145

I haven't had time to dig yet.

**Comment by geoffwatts** [comment]
I set duration to 0 (instead of nil) in line 405 (might be 404 your end, added a few CRs at the top), and that seems to have made it happier.

I'll have a deeper look in the morning.  Thanks again for this!

**Comment by autoSteve** [comment]
The 408: attempt to compare number with nil should be gone in the last commnit. The orphan? Whoa... Expected level 571 in an eight bit lighting group number that should be 0..255? I got nothin' at this stage.

**Comment by autoSteve** [comment]
Added an optional device exposes summary in device discovery. Handy to set up sensors/3-way keywords, etc. Looks something like this in the log:

```
Device exposed property summary
-------------------------------
Bedroom 2 smart plug: linkquality, state
Den router: linkquality
Foxy's bedside light: brightness, color, color_temp, color_temp_startup, effect, hue, linkquality, power_on_behavior, saturation, state, x, y
Foxy's electric blanket: linkquality, state
Hutch environment: battery, humidity, linkquality, temperature, voltage
Steve's bedside light: brightness, color, color_temp, color_temp_startup, effect, hue, linkquality, power_on_behavior, saturation, state, x, y
Steve's electric blanket: linkquality, state
Turntable: linkquality, state
```

With detailed logging enabled the script log window will miss showing it because so much is going on at startup.

**Comment by autoSteve** [comment]
Transitioning my Hue bedside lights to off via a scene triggered by my "All off" button last night worked flawlessly, by the way. Chalk and cheese compared to the Hue bridge.

There was absolutely zero latency before the transition off started, and the script got the timing spot on.

I should have ditched the useless bridge years ago...

When the time comes for you, though, I do see some odd behaviour in Home Assistant. State is fine, but brightness recorded in Mosquitto does not match the UI. e.g. If something is set at 30% in C-Bus/MQTT it will show as on, but slider all the way down. I think this is almost certainly an HA bug when using the json schema for discovery, or I'm missing something in Z2M config (but can't think what). Z2M looks to be doing everything perfectly.

**Comment by autoSteve** [comment]
After MUCH frigging around, Home Assistant is displaying and operating the lights correctly.

Through trial and error, Home Assistant started acting correctly when I set a colour on a light. I did that out of desperation after a couple of hours and facepalmed. 🤦🏻

HA bug? Z2M bug? Dunno who to blame for this one.

I've added configuring change reporting for on/off and also current colour X & Y, along with the existing brightness. Z2M will throw errors if lights do not support the clusters involved, and I need to fix this, as lights do report their clusters in the bridge/devices topic, and this will need to be grabbed to cope with very dumb dimmable lights that don't do the whole colour thing.

After script restart, turning on and off lights in HA sorts their status after a single report comes in, because that now includes the current colour set in the light.

I'm also thinking of setting a flag in AC storage when reporting gets configured for a device, so it doesn't re-configure the same thing on every script restart, which will be imporant for deployments with dozens of lights. A mechanism to clear that storage if needed would be good, too.

But here's me going all off-topic. How goes the race condition testing, @geoffwatts?

**Comment by autoSteve** [comment]
No need to muck about with AC storage. The bridge/devices payload already has what's configured for reporting, so we delta set what's missing now.

**Comment by geoffwatts** [comment]
Think we're there with the race condition, can't seem to lock a light out.  However(!)

The transitions are doing some strange things to some of my dimmers, though, and I haven't been able to figure it out yet.

If I turn a light off (to 254/254) from the Zigbee end, the script is somehow picking this up:
* string: Set 0/56/213 to 512
* string: Publish 0/56/213 zigbee2mqtt/Geoff bedside/set, {"state":"ON","brightness":8}
* string: Warning: Removed orphaned C-Bus ignore flag for 0/56/213, the expected level 264 was never received - value when set was 67

I looked on the mqtt side, the colour temp is set to 500, but I can't see where the 500 is coming from.

Will have a dig if I can in a few hours.

**Comment by geoffwatts** [comment]
Well FML, this is a bug with my lights, I think.

I disabled the script, and for some crazy reason, when the light is set to full brightness (254), zigbee2mqtt publishes a brightness of 1000 to mqtt when it's changed.  Suspect it's not being scaled correctly somewhere.

Everything looks good in the zigbee2mqtt UI (because it doesn't render the update in the UI), and works perfectly as well.  If I press the refresh button (issuing a GET), the "correct" brightness is written back to mqtt.

HASS just thinks it's on 100% if it's > the max.

I think this might be a Tuya issue (who are the manufacturer of the dimmers), and a workaround is probably to send a GET for the brightness, but how irritating.  And if the brightness is controlled outside of cbus, how does the script know if this is a valid or invalid brightness on mqtt?

How do you feel about setting some lights to unidirectional (they don't read, only write) with a parameter?

**Comment by autoSteve** [comment]
> How do you feel about setting some lights to unidirectional (they don't read, only write) with a parameter?

FML... 🤣🤣🤣

That could be done. (You might need to find a more well behaved dimmer...)

It irks me (ewww, ewww, 🤢), but it can be done.

The code already features a "special" c/u/d table, designed for just this kind of use case. For example, set a keyword of tuyasux and it will set a true in that special table that can be acted upon when setting up the devices...

So how to "act", though? If it's a "special" device (that only a mother could love), do we issue a "get" before doing anything, then act? Or simply ignore this "special" one?

Please don't make me buy a Tuya dimmer... 🤮

**Comment by geoffwatts** [comment]
Some are kinda nice hardware, but I have similar feelings re Tuya: https://www.australianlightingandfans.com.au/mercator-ikuu-smart-rotary-dimmer-mechanism-zigbee.html

I actually think it's a big in herdsman-converters for the particular dimmer I have.  Will look a bit more in the morning.

But good news: not you!  Let's merge, I think this is working great.

**Pull request merged**
